# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170419_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shortbio',
            new_name='short_bio',
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
